# These settings must match:
# - Port numbers specified in the ABB robot controller's system configurations for EGM communication.
egm:
  channel_1:
    port_number: 6511

# These settings must match:
# - Joint names extracted from the ABB robot controller.
#
# Please see http://wiki.ros.org/joint_limits_interface for more details about joint limits.
joint_limits:
  default_velocity_scaling_factor: 1.0
  default_acceleration_scaling_factor: 1.0
  
  joint_1:
    has_velocity_limits: true
    max_velocity: 8.72664
    has_acceleration_limits: true
    max_acceleration: 8.72664
  joint_2:
    has_velocity_limits: true
    max_velocity: 8.72664
    has_acceleration_limits: true
    max_acceleration: 8.72664
  joint_3:
    has_velocity_limits: true
    max_velocity: 8.72664
    has_acceleration_limits: true
    max_acceleration: 8.72664
  joint_4:
    has_velocity_limits: true
    max_velocity: 11.1701
    has_acceleration_limits: true
    max_acceleration: 11.1701
  joint_5:
    has_velocity_limits: true
    max_velocity: 11.1701
    has_acceleration_limits: true
    max_acceleration: 11.1701
  joint_6:
    has_velocity_limits: true 
    max_velocity: 14.66076
    has_acceleration_limits: true
    max_acceleration: 14.66076
