joint_state_controller:

  type: joint_state_controller/JointStateController
  publish_rate: 250
  
egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController

  constraints:
#    goal_time: 0.6
    stopped_velocity_tolerance: 0.1

    joint_1: {trajectory: 0.1, goal: 0.001}
    joint_2: {trajectory: 0.1, goal: 0.001}
    joint_3: {trajectory: 0.1, goal: 0.001}
    joint_4: {trajectory: 0.1, goal: 0.001}
    joint_5: {trajectory: 0.1, goal: 0.001}
    joint_6: {trajectory: 0.1, goal: 0.001}
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6


